#!/bin/sh
# 
# prerm maintainer script for the Debian tex-common package.

# remove dirs in /usr/local if empty

set -e

case $1 in
  remove)
    rmdir /usr/local/share/texmf 2>/dev/null || true
    ;;
esac

#DEBHELPER#


